import { c as create_ssr_component } from "../../../../chunks/ssr.js";
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  return `<title data-svelte-h="svelte-s96llg">october&#39;s blog post</title> <p data-svelte-h="svelte-fmnkeu">meows scarily</p> <figure style="margin: 0;" data-svelte-h="svelte-pzax3w"><img src="/images/blog/oct/daifuku.jpg" style="max-width: 300px; width: 300px; height: 300px; object-fit: cover;" alt="daifuku in little tokyo"> <figcaption style="text-align: left;"><em>sweetness is in the air, and i am placed in the present!</em></figcaption></figure> <p data-svelte-h="svelte-nu7ff9">october has been wonderful and joyous! i’ve been enjoying the balance in
    between the lingering of summer heat and the emergence of the winter chill.
    oh, how i’m excited to deck out in oversized heavyweight hoodies, thermal
    pants under cargo pants, and overly platform-ed sneakers. yay!</p> <figure style="margin: 0;" data-svelte-h="svelte-16w3dl5"><img src="/images/blog/oct/bunny.jpg" style="max-width: 300px; width: 300px; height: 300px; object-fit: cover;" alt="daifuku in little tokyo"> <figcaption style="text-align: left;"><em></em></figcaption></figure> <h2 data-svelte-h="svelte-1lpilds">i might taste you on my lips forever</h2> <ul data-svelte-h="svelte-6akxut"><li>kinako daifuku from fugestu-do</li> <li>black truffle pasta from il pastaio</li> <li>banana pie and white coffee ice cream at uchi</li> <li>smith’s strawberry lip salve</li> <li>sleepytime tea for drowsy bear time</li> <li>hot coffee kisses, brown sugar on my tongue</li> <li>yuzu tamago pan</li> <li>al-dente udon swimming in light dashi broth</li></ul> <figure style="margin: 0;" data-svelte-h="svelte-uj8c5s"><img src="/images/blog/oct/bags.jpg" style="max-width: 300px; width: 300px; height: 300px; object-fit: cover;" alt="daifuku in little tokyo"> <figcaption style="text-align: left;"><em></em></figcaption></figure> <h2 data-svelte-h="svelte-178kayb">new songs that i have been enjoying (or revisiting)</h2> <ul data-svelte-h="svelte-1uf27vs"><li>arm&#39;s length by mallrat (tell me true, what am i to you?)</li> <li>good stuff by bnny</li> <li>i finally understand by charli xcx</li> <li>undo u (4x4 mix) by ninajirachi</li> <li>image by magdalena bay</li></ul> <figure style="margin: 0;" data-svelte-h="svelte-v3u7bb"><img src="/images/blog/oct/truffle.jpg" style="max-width: 300px; width: 300px; height: 300px; object-fit: cover;" alt="daifuku in little tokyo"> <figcaption style="text-align: left;"><em></em></figcaption></figure> <figure style="margin: 0;" data-svelte-h="svelte-4s5q34"><img src="/images/blog/oct/uchi.jpg" style="max-width: 300px; width: 300px; height: 300px; object-fit: cover;" alt="daifuku in little tokyo"> <figcaption style="text-align: left;"><em></em></figcaption></figure>`;
});
export {
  Page as default
};
